services:
  jni-bun-template:
    build: .
    image: registry.mopore.org/jni/jni-bun-template:latest
    container_name: jni-bun-template
    env_file:
      - .env
    # restart: unless-stopped
    environment:
      - TZ=UTC
      - LOG_SETUP=prod
    command: ["test arg value from docker-compose.yaml"]